import Head from 'next/head'
import * as THREE from 'three'
import { useRef } from 'react'
import useThree, { Options } from '../THREE/useThree'



export default function Home() {
	const reff = useRef(null)

	const material = new THREE.LineBasicMaterial({
		color: 0x00ffff,
	})
	const points = [
		new THREE.Vector3(-10, 0, 0),
		new THREE.Vector3(0, 10, 0),
		new THREE.Vector3(10, 0, 0)
	]

	const geometry = new THREE.BufferGeometry().setFromPoints(points)
	const line = new THREE.Line(geometry, material)

	const { scene } = useThree(new Options({ 
		canvas: reff, 
		antialias: true,
		animate: 
		function animate() {
			line.rotation.x += 0.01
			line.rotation.y += 0.01
		},
	}))	

	scene.add(line)

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div id='container'></div>

			<canvas style={{
				position: 'fixed', transition: 'all .4000s linear',
				top: 0, left: 0, width: '100vw', height: '100vh', zIndex: '-1'
			}} ref={reff} id='' width={1000} height={1000}></canvas>
		</>
	)
}
